theme = "blist"
languageCode = "en-US"
baseurl = "/"
title = "FGC Basel"

[params]
description = "Fighting Game Community Basel"
name = "FGC Basel"

# Enable the darkmode toggle in header
darkModeToggle = true

# Enable search in header
enableSearch = true

# Custom copyright - optional
copyright = "Hey, come on!"
favicon = "favicon.svg"

# Color for the intro details and social links block, not applicable for dark mode
# Supported values: Any color from TailwindCSS default colors
# Reference: https://tailwindcss.com/docs/customizing-colors
ascentColor = "bg-gray-200"

[params.homepage]
title = "Fighting Game Community Basel"
description = "This is the Homepage of the Fighting Game Community Basel."
photo = "/banner.jpg"

[params.homepage.social]
title = "About"
description = "Work in progress..."

[[menu.main]]
name = "Versus Wednesdays"
url = "/versus-wednesdays"

[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
